# SwiftLint Configuration for X68Mac
# This configuration provides basic code quality rules for the project

# Disable rules that may conflict with existing codebase
disabled_rules:
  - trailing_whitespace # Allow existing whitespace patterns
  - line_length # Allow longer lines for complex emulation code

# Enable additional rules for better code quality
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Customize rule parameters
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 15
  error: 25

# Exclude certain paths
excluded:
  - Carthage
  - Pods
  - .build
  - c68k # Exclude C/C++ emulation core
  - px68k # Exclude C/C++ emulation core

# Include specific file types
included:
  - "*.swift"

# Reporter type
reporter: "xcode"

